### ISSUE TITLE
The intersection solution is not correct

### ISSUE THREAD

**Issue by HDKHALILI** [FrontendMasters/fm-snippets#6]
The current solution for the intersection only works with two arrays.
The  -1 from the length means there will always be one item left in the array.
`for (let k = 1; k < arguments.length - 1; k++)`

The condition only checks the item of first array against the other arrays in sequence, if an item from any array matches an item from the first array it will return true. There is no check for an item to exist in all array.
`if (arguments[0][i] === arguments[k][j])`

**Comment by mauriciord506** [comment]
Hello, Yes I agree the current solution is very bad. Not only because it does not give the proper output, while doing other test cases, but because of the fact that. It does not show how to use reduce, nor it makes use of any of the previous functionality created for the exercises like, forEach, map, etc.

I solved it using the reduce, However, I had to create a filter method because I like to have it on my Swiss knife.

Since my solution is depending on the previous functionality used on the exercise. This is whole code:

`// Challenge 3`
`function map(array, callback) {`
	`var tempArray = [];`
  `forEach(array,function (item){`
    `tempArray.push(callback(item));`
 ` });`
 ` return tempArray;`
`}`

`// Challenge 4`
`function forEach(array, callback) {`
	`for(var i = 0; i < array.length; i++) {`
    `callback(array[i],i);`
 ` }`
`}`

`//My Filter Function not used on the exercise`

`function filter (array,callback) {`
` var filteredItems = [];`
  `forEach(array,function(item){`
    `if(callback(item)) {`
      `filteredItems.push(item)`
   ` }`
  `})`
 ` return filteredItems;`
`}`

`//Extension 1 already reused forEach on map.`
`function mapWith(array, callback) {`
 	`return map(array,callback);`
`}`

`//Extension 3`
`function reduce(array, callback, initialValue) {`
  `var accumulator = initialValue;`
  `forEach(array,function(nextItem){`
    `accumulator = callback(accumulator,nextItem);`
 ` });`
  
 ` return accumulator;`

`}`

`function intersection(arrays) {`
	`var arg = mapWith(arguments,function (array){`
		`return array;`
	`});`
  `var intersected = reduce(arg,function(acc,nxtItem){`
    `return filter(acc,function(item){`
      `return nxtItem.indexOf(item) > -1;`
    `})`
 ` },arg[0])`
  `return intersected;`
}

`console.log(intersection([5, 10, 15, 20], [15, 88, 1, 5, 7], [1, 10, 15, 5, 20]));`

Regards,
Mauricio.
