### ISSUE TITLE
Challenge 3-part2 solution in Asynchronocity solutions doesn't work as expected

### ISSUE THREAD

**Issue by sivavemulapalli** [FrontendMasters/fm-snippets#9]
The solution to part2 of challenge 3 in asynchronocity exercise in hardparts doesn't work as expected. It doesn't print "Howdy" messages at the interval of 2 seconds. It print all 5 at the sametime after the "End of Challenge 3" message gets logged.

**Comment by anmpog** [comment]
I did some research on this because I was observing the same behavior described above. What I found (someone please correct me if I'm wrong) is this:

The first place my mind went was to write a for loop that would iterate `totalTimes/intervalTime' (both given in seconds so if you wanted to console log "howdy" every 2 seconds for 10 seconds you would expect 5 console logs to occur in a world where you could start the timers concurrently).  The body of the for loop would create a new "timeout" that would fire the `console.log` (or function) every `intervalTime * 1000` milliseconds.

The problem is that every time the for loop iterates, `setTimeout`'s function is placed in the event loop. The for loop executes nearly instantly, meaning that in extremely short order all the `setTimeout` calls are added to the event loop, and they all execute almost simultaneously.  

I used something like this, but it's hard to know if this is a good solution. It behaves closer to what would be expected if the goal is to mimic the behavior of `setInterval`, but I'm sure someone who knows more could find fault with it:

```js
function everyXsecsForYsecs(callback, intervalTime, totalTime) {
  for (let i = 0; i < totalTime/intervalTime; i++) {
    setTimeout(sayHowdy, (intervalTime * (1000 * i)))
  }
}

everyXsecsForYsecs(sayHowdy, 3, 13)
```

**Comment by mrfleegan** [comment]
I believe you would need to let `i` start with 1 to get the initial timer to act correctly.  I've modified your function and perhaps it's a bit closer:

`function everyXsecsForYsecs(callback, intervalTime, totalTime) {
  for(let i = 1; i < Math.floor(totalTime / interval) + 1; i++) {    
    setTimeout(callback, interval * (i * 1000));
  }
}

everyXsecsForYsecs(sayHowdy, 3, 13)`

I also added `Math.floor` to handle rounding.

**Comment by mrfleegan** [comment]
Yours is definitely closer than the answer given.  I believe you'll need to start `i` at 1 instead of zero to correctly set the first timeout.  I've modified it and added `Math.floor` to handle rounding issues below:

```
function everyXsecsForYsecs(callback, interval, totalTime) { 
  for(let i = 1; i < Math.floor(totalTime / interval) + 1; i++) {    
    setTimeout(callback, interval * (i * 1000));
  }
  
  function stop() {
    clearInterval(myInterval);
  }
}
```
If you test it out, let me know if you find any issues with the changes.
